sudo: required

language: generic

git:
  depth: false

dist: xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker pull moussavdb/build-java-native

script:
  - chmod +x src/main/scripts/win64/build.sh
  - travis_retry docker run -v $PWD:/src -v $HOME/.m2:/root/.m2 -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -e BRANCH=$TRAVIS_BRANCH  -e VAULT_TOKEN=$VAULT_TOKEN moussavdb/build-java-native
